### ISSUE TITLE
golib.csproj not compiling in the current version

### ISSUE THREAD

**Issue by loudenvier** [GridProtectionAlliance/go2cs#28]
The following methods in `sstring.cs` are preventing it from compiling:

```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)] 
public static implicit operator sstring(slice<byte> value) => new(value);

[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static implicit operator sstring(slice<char> value) => new(value);
```

It gives two error messages: 

- "_error CS8166: Cannot return a parameter by reference 'value' because it is not a ref parameter_"
- "_error CS8347: Cannot use a result of 'sstring.sstring(in slice<byte>)' in this context because it may expose variables referenced by parameter 'value' outside of their declaration scope_"

I've cloned the repo locally then opened cs2go.sln in Visual Studio Community (latest version). Since golib.cs does not compile, I'm really stuck! Any help would be greatly appreciated! 

Visual Studio suggested the following fiz:
```csharp
 [MethodImpl(MethodImplOptions.AggressiveInlining)]
 public static implicit operator sstring(slice<byte> value) => new(value: value);
```

But it didn't work.  So I removed the `in` clause in the constructors affected:

```csharp
public sstring(in slice<char> value) : this(value.ToArray()) { }
```

But I don't know the performance implications of these changes...

**Comment by ritchiecarroll** [comment]
Interesting, this wasn't happening in earlier versions of VS.  Guess the compiler is getting better about finding risky situations with `ref struct` operations. I have checked in a fix for these convenience functions that just convert to `.ToArray()` early.

*Technical Details:* this `go.sstring` structure is just an experiment with a stack allocated string type which could theoretically improve performance of string operations by avoiding heap allocations, better matching its Go string counterpart when operating in stack-oriented code. Exiting to the heap will still require `go.@string`, although it is a little tricky to determine when this is required -- and even trickier when you are targeting general purpose pre-compiled intermediate language (IL) libraries.  That said, we may be to put in a transpilation option that better matches Go for project optimizations by basically compiling everything together, i.e., all needed/referenced source, for a given project that can more easily detect when a structure needs heap allocation because it leaves the stack for a given executable.
