### ISSUE TITLE
Needed help on some issues faced after converting golang to c#

### ISSUE THREAD

**Issue by Rashmi-Rajashekhara** [GridProtectionAlliance/go2cs#3]
Hi,

I am trying to convert an already existing go lang code to c#. 
After converting the corresponding file to c#, there are some dependencies issue. 

Even though I have downloaded the corresponding go standard libraries, I am still facing the issue saying that it cant find the standard libraries. 

![image](https://user-images.githubusercontent.com/42083967/60093809-ff2bd880-9767-11e9-92d6-7fad070a1cae.png)

Kindly let me know how to resolve this issue. 

Regards,
Rashmi

**Comment by ritchiecarroll** [comment]
Converting the Go standard library is a remaining task. My attention is currently averted onto other _paying_ projects. I haven't circled back to this code lately, still looking for some help to complete the remaining tasks. Let me know if you are interested. Thanks!

**Comment by ritchiecarroll** [comment]
Recently been making progress here, started work on a simply Go standard library conversion to act as a proxy for use case example conversions. Once these are complete, will try recompiling standard library again...

**Comment by ritchiecarroll** [comment]
An initial pass at converting the full Go standard library has been completed, you can find the results here:
https://github.com/GridProtectionAlliance/go2cs/tree/master/src/go-src-converted

The simple manually converted subset of the Go standard library is what current conversion depend upon:
https://github.com/GridProtectionAlliance/go2cs/tree/master/src/gocore

But with the full standard library now converting successfully, steps to merge automated and manual conversions - and improve conversion quality - can now begin.

**Comment by juliolitwin** [comment]
@ritchiecarroll it's already possible to convert a project?  I saw you converted the standard library 

I am looking to test this following project::
https://github.com/topfreegames/pitaya/

**Comment by ritchiecarroll** [comment]
Yes, with caveats, it likely won't immediately compile without work - for large projects, with many dependent project, perhaps much work.

Work is progress to better handle code compilation uses to make them work properly. So at the moment, the tool will help you along, perhaps as much as 80% to 90%, but for the moment, that last 10 to 20% will be on the user.

I am confident based on experience so far, most pure Golang translations in the future will be able to hit near 100% conversion, that is, run immediately - but the project is not quite there yet...

FYI, that's why I haven't had an official release yet - I think if can get most simple apps at 100% and complex apps at > 95%, I will create an initial release.

Thanks,
Ritchie
